# replaces default /plugin command with what is displayer in /reloader list
# warning: not set to use perms
pl: true
# time between automatic reloads
timer:
  autoreload: false
  hours: 24
  minutes: 0
  seconds: 0
# Plugins exempt from unload/disable/reload
# (works like permission.yml files!)
exempt:
  - 'WorldGuard'
  - 'Reloader'