# replaces default /plugin command with what is displayer in /reloader list
# use reloader.list permission to allow users to see this
pl: true
# If set to true the default /pl is inaccessible.
# users with reloader.list perm can still see the /reloader list version
default-pl: false
# time between automatic reloads
timer:
  autoreload: false
  hours: 24
  minutes: 0
  seconds: 0
# Plugins exempt from unload/disable/reload
# (works like permission.yml files!)
exempt:
  - 'WorldGuard'
  - 'Reloader'
