name: Reloader
description: Reload or disable plugins at will
version: 3.4

authors: [jmgr2007, Omnivion]

main: 'me.jmgr2007.Reloader.Reloader'

commands:
  reloader:
    description: index command for Reloader
    usage: '/reloader for help'

permissions:
  reloader.reload:
    description: Permission to reload plugins
  reloader.list:
    description: see reloader's plugins list
